
name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - uses: actions/checkout@v2
      - name: Backport
        uses: m-kuhn/backport@v1.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
